"""Add test calendar events via the running API server."""
import json
import urllib.request

API = "http://localhost:8000/api/calendar/events"

events = [
    {
        "title": "Pomiar u klienta Nowak",
        "event_type": "pomiary",
        "type": "measurement",
        "project_id": 1,
        "date_from": "2026-04-27",
        "date_to": "2026-04-27",
        "start_at": "2026-04-27",
        "end_at": "2026-04-27",
        "all_day": True,
        "client_name": "Piotr Nowak",
        "project_ref": "ZAM-101",
        "assigned_to": "Jan Pomiar",
        "location": "ul. Dluga 15, Krakow",
        "notes": "Kuchnia + lazienka, wziac dalmierz",
        "status": "planned",
    },
    {
        "title": "Produkcja szafek ZAM-098",
        "event_type": "zlecenie",
        "type": "production",
        "project_id": 1,
        "date_from": "2026-04-27",
        "date_to": "2026-04-29",
        "start_at": "2026-04-27",
        "end_at": "2026-04-29",
        "all_day": True,
        "client_name": "Anna Kowalska",
        "project_ref": "ZAM-098",
        "assigned_to": "Marek CNC",
        "notes": "Korpusy + polki, plyta laminowana dab",
        "status": "in_progress",
    },
    {
        "title": "Montaz kuchni Wisniewska",
        "event_type": "montaz",
        "type": "installation",
        "project_id": 1,
        "date_from": "2026-04-28",
        "date_to": "2026-04-29",
        "start_at": "2026-04-28",
        "end_at": "2026-04-29",
        "all_day": True,
        "client_name": "Maria Wisniewska",
        "project_ref": "ZAM-095",
        "assigned_to": "Tomek Montaz",
        "location": "ul. Kwiatowa 8, Warszawa",
        "notes": "12 modulow, wziac uchwyt blatu",
        "status": "confirmed",
    },
    {
        "title": "Wycena projektu Kowalski",
        "event_type": "wstepna_wycena",
        "type": "meeting",
        "project_id": 1,
        "date_from": "2026-04-28",
        "date_to": "2026-04-28",
        "start_at": "2026-04-28",
        "end_at": "2026-04-28",
        "all_day": True,
        "client_name": "Jan Kowalski",
        "project_ref": "ZAM-102",
        "assigned_to": "Emilia Kmita",
        "notes": "Kuchnia nowoczesna, budzet ok 35tys",
        "status": "planned",
    },
    {
        "title": "Lakierowanie frontow ZAM-097",
        "event_type": "zlecenie",
        "type": "production",
        "project_id": 1,
        "date_from": "2026-04-29",
        "date_to": "2026-04-30",
        "start_at": "2026-04-29",
        "end_at": "2026-04-30",
        "all_day": True,
        "client_name": "Katarzyna Zielinska",
        "project_ref": "ZAM-097",
        "assigned_to": "Adam Lakier",
        "notes": "RAL 9010 mat, 24 fronty",
        "status": "planned",
    },
    {
        "title": "Spotkanie z architektem Nowickim",
        "event_type": "wstepna_wycena",
        "type": "meeting",
        "project_id": 1,
        "date_from": "2026-04-29",
        "date_to": "2026-04-29",
        "start_at": "2026-04-29",
        "end_at": "2026-04-29",
        "all_day": False,
        "client_name": "Arch. Nowicki",
        "project_ref": "ZAM-103",
        "assigned_to": "Emilia Kmita",
        "location": "Biuro - sala konferencyjna",
        "notes": "Mebloscianka salon",
        "status": "confirmed",
    },
    {
        "title": "Transport materialow - hurtownia",
        "event_type": "zamowienie_mat",
        "type": "transport",
        "project_id": 1,
        "date_from": "2026-04-30",
        "date_to": "2026-04-30",
        "start_at": "2026-04-30",
        "end_at": "2026-04-30",
        "all_day": True,
        "project_ref": "ZAM-101",
        "assigned_to": "Jan Pomiar",
        "location": "Hurtownia Kronopol",
        "notes": "Plyta MDF 18mm, obrzeze ABS",
        "status": "planned",
    },
    {
        "title": "Poprawki szuflad ZAM-094",
        "event_type": "poprawki",
        "type": "service",
        "project_id": 1,
        "date_from": "2026-04-30",
        "date_to": "2026-04-30",
        "start_at": "2026-04-30",
        "end_at": "2026-04-30",
        "all_day": True,
        "client_name": "Robert Maj",
        "project_ref": "ZAM-094",
        "assigned_to": "Tomek Montaz",
        "notes": "Wymiana prowadnic szuflad (reklamacja)",
        "status": "in_progress",
    },
    {
        "title": "Dzien wolny - Swieto Pracy",
        "event_type": "urlop",
        "type": "other",
        "project_id": 1,
        "date_from": "2026-05-01",
        "date_to": "2026-05-01",
        "start_at": "2026-05-01",
        "end_at": "2026-05-01",
        "all_day": True,
        "notes": "Dzien ustawowo wolny od pracy",
        "status": "confirmed",
    },
    {
        "title": "Pomiar u klienta Lewandowski",
        "event_type": "pomiary",
        "type": "measurement",
        "project_id": 1,
        "date_from": "2026-05-02",
        "date_to": "2026-05-02",
        "start_at": "2026-05-02",
        "end_at": "2026-05-02",
        "all_day": False,
        "client_name": "Andrzej Lewandowski",
        "project_ref": "ZAM-104",
        "assigned_to": "Jan Pomiar",
        "location": "ul. Ogrodowa 22, Krakow",
        "notes": "Szafy wnekowe sypialnia + garderoba",
        "status": "planned",
    },
    {
        "title": "Produkcja korpusow ZAM-101",
        "event_type": "zlecenie",
        "type": "production",
        "project_id": 1,
        "date_from": "2026-05-04",
        "date_to": "2026-05-06",
        "start_at": "2026-05-04",
        "end_at": "2026-05-06",
        "all_day": True,
        "client_name": "Piotr Nowak",
        "project_ref": "ZAM-101",
        "assigned_to": "Marek CNC",
        "notes": "Kuchnia - 14 korpusow",
        "status": "planned",
    },
    {
        "title": "Montaz kuchni Zielinska",
        "event_type": "montaz",
        "type": "installation",
        "project_id": 1,
        "date_from": "2026-05-07",
        "date_to": "2026-05-08",
        "start_at": "2026-05-07",
        "end_at": "2026-05-08",
        "all_day": True,
        "client_name": "Katarzyna Zielinska",
        "project_ref": "ZAM-097",
        "assigned_to": "Tomek Montaz",
        "location": "ul. Parkowa 5, Krakow",
        "notes": "Po lakierowaniu, sprawdzic kolor na miejscu",
        "status": "planned",
    },
]

ok = 0
fail = 0
for ev in events:
    data = json.dumps(ev).encode("utf-8")
    req = urllib.request.Request(API, data=data, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            result = json.loads(resp.read())
            print(f"  OK: {ev['title'][:45]:<45} -> id={result.get('id')}")
            ok += 1
    except Exception as e:
        print(f"  FAIL: {ev['title'][:45]:<45} -> {e}")
        fail += 1

print(f"\nDodano: {ok}, bledy: {fail}")

# Verify
req2 = urllib.request.Request(f"{API}?limit=50")
with urllib.request.urlopen(req2, timeout=5) as resp:
    result = json.loads(resp.read())
    total = len(result.get("events", []))
    print(f"Lacznie zdarzen w API: {total}")
